### ISSUE TITLE
Expected Behaviors: Bare Necessities for Evora

### ISSUE THREAD

**Issue by mattketk** [UWMRO/Instruments#2]
# ~~Main Controls~~

~~1. Initialize Telescope~~
~~2. Confirm Zenith position~~
~~3. Shutdown Telescope~~

# Temperature Controls

1. Set Temperature: input a float to set target cooling temperature
2. Get Temperature: poll for current sensor temperature
3. Check if cooling finished: output boolean based on whether current temperature at target temperature
4. Stop Cooling

# ~~Filter Wheel Controls~~

~~1. Set Filter Wheel~~
~~2. Get Current Filter Wheel~~
~~3. Check if filter is moving into place~~

# Exposure Controls

1. Biases, Flats, Darks, Objects Image Types
2. Exposure Time
3. Single, Real Time, Series
4. Abort Exposure

**Comment by ejgl** [comment]
Exposure Controls Details:
1. Biases, flats, darks, and objects are all different image types, written into the header of the fits file. Biases are zero-second exposures with the shutter closed, and therefore should not be an option. Flats are exposures of varying lengths of times with the shutter open, and Darks are exposures of varying length with the shutter closed. Objects are essentially the same as a flat, with the only difference being that the object type "Object" is written into the header instead of "Flat", for the purpose of denoting exposures as an Object.
2. Setting exposure time is needed for the purpose of taking flats/objects and darks. Exposure time should be set in total amount of seconds (example: 60 seconds, 120 seconds, etc.)
3. Single, Real Time, Series are different settings on ways to take images. Single takes and saves a single image, real time makes the camera pretend it's a "video recorder" and takes as many images as possible over and over again without saving them. Series takes a integer input and takes and saves that many images.
4. Abort exposure halts the current exposure process.

**Comment by ojf** [comment]
Setting up the Camera (UX Story)

1. Initialize the camera: calls several Andor methods to prepare camera for use--see Andor example code for specific andor methods called.
2. User cools the camera to -82 degrees: typically user enters the temperature setpoint as a number (integer?) and then activates the cooler.
3. User observes camera's current temperature as it cools
4. User sets a destination directory for images (is this necessary, or will web browser save the destination directory?)

**Comment by ojf** [comment]
Using the Camera (UX Story). Order of operations isn't important in this case, settings persist between exposures.

- (we don't typically change these settings, they were hidden in a menu in Evora) The user chooses the binning (1x1 or 2x2) and readout rates. Default for science images is 2x2 and 0.05 MHz. Possibly automatically faster readouts for Real Time exposures.
- The user decides what type of image to take: bias, flat, dark, or object. Biases automatically set a zero second exposure time and do not activate the shutter. Darks do not activate the shutter, but do have an exposure time. All others have an exposure time and use the shutter, the only different is in the meta-data saved to the final image.  
- The user decides how many exposures to take: a single exposure, a series of n exposures (n is usually 5 or 10, recommend building it for 1-99), or "Real Time" exposures. Real Time takes exposures continuously until cancelled, like a low-framerate video. 
- The user enters an exposure time (e.x.: 0.5sec, 5sec, 120sec, etc.) unless the image type of bias.
- The user chooses a filename (or basename for a series exposure, i.e. basename_001.fits)
- The user initiates an exposure or series of exposures (depending on exposure type)
- The user observes the progress of the exposure, which they could abort--this is how Real Time exposures are stopped.

**Comment by ojf** [comment]
Required steps to shut down the Camera (UX Story)

1. User turns off cooler
2. User observes camera warm up
3. User shuts camera down when warm (Andor documentation specifies a temperature)

This could be substantially automated (i.e. user could choose to shutdown, server would warm camera, report temperature and shut down when safe).

**Comment by ojf** [comment]
Writing this, it seems like we'll need the camera to report back its temperature & exposure progress. For real time exposures to work I think we'll need to display the image in the UI--not sure it'll work to download series of images...
